version: "3"
services:
  keep_smiling_back:
    container_name: keep-smiling-back
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://keep_db:3306/keepsmiling?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USER=root
      - DB_PASSWORD=R55Gt9Bf
    restart: always
    depends_on:
      keep_db:
        condition: service_healthy

  keep_db:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: R55Gt9Bf
      MYSQL_PASSWORD: R55Gt9Bf
      MYSQL_DATABASE: keepsmiling
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
volumes:
  mysql-data:
    external: false